### PR TITLE
(Worklet) Add cornerbox demo

### PR DESCRIPTION
**Pull request by jerosoler**
image

Demo: https://jerosoler.github.io/cornerbox/

### CODE REVIEW

**Comment by jerosoler** [comment]
@googlebot I signed it!

**Comment by una** [comment]
Thanks for this PR! I love this demo! A few questions:

1. I notice that the corners are still slightly visible, even when `--cornerbox-line` is at 0. Is it possible to take this full off-canvas?
2. I would have the range be from 0 for `--cornerbox-line` because I think this is a neat effect that can animate in
3. The second variable `--cornerbox-lenght` has a typo, but might also make more sense to be called the `--cornerbox-width` instead. Similarly, I might rename `--cornerbox-line` to be `--cornerbox-length`, because it feels more descriptive

**Comment by jerosoler** [comment]
Hello @una 

Thanks a lot! I like that you like it!

I have uploaded the corrections you indicate. You're right ;)
Good work!

**Comment by una** [comment]
Nice one!

**Pull request merged**
