### PR TITLE
feat: Add houdini-noise by Jhey Tompkins

### PR DESCRIPTION
**Pull request by jh3y**
- New worklet for HSL configured background noise.
- Fun when combined with `:hover` effects 😄

### CODE REVIEW

**Comment by nucliweb** [comment]
Thanks a lot for the contribution @jh3y, one suggestion:

**Can you add README to the package?**
_Take a look to this sample https://github.com/CSSHoudini/css-houdini/tree/main/src/lines_

**Comment by nucliweb** [comment]
One more thing, can you add the polyfill in the demo to add support to Firefox?

Thanks

**Comment by jh3y** [comment]
Fixed!

However. There is one issue. The paint polyfill isn't actually poly filling `CSS.registerProperty` as it says on the `README` 👎

**Comment by nucliweb** [comment]
Thanks @jh3y , one more thing... can you move the `dependencies` to `devDependencies`, you don't need them to run the worklet, and the users will install all the packages when they install your worklet.

https://github.com/jh3y/houdini-noise/blob/main/package.json#L29-L38

Thanks

**Comment by nucliweb** [comment]
> Fixed!
> 
> However. There is one issue. The paint polyfill isn't actually polyfilling `CSS.registerProperty` as it says on the `README` 👎
> 
> See [unpkg file](https://unpkg.com/css-paint-polyfill@2.0.0/dist/css-paint-polyfill.js). No mention of `CSS.registerProperty`. However, it is polyfilled in `src/index.js`. I don't think it's being bundled into the `dist` files.

Can you help with this @developit ?

**Comment by jh3y** [comment]
Done. Sorry, I was trying out different packages to set up and run locally. Forgot to shift them back to `devDependencies` 👍

**Comment by zhenyanghua** [comment]
I tried the build locally and found the `CSS.registerProperty` is present. It is also present in the `next` release is `3.2.0` and on unpkg you could find the polyfill at [https://unpkg.com/css-paint-polyfill@next/dist/css-paint-polyfill.js](https://unpkg.com/css-paint-polyfill@next/dist/css-paint-polyfill.js). 

Note that the current `latest` release is `2.0.0`, and the `next` release is `3.2.0`.

**Review by nucliweb — APPROVED** [review]

**Review by nucliweb — CHANGES_REQUESTED** [review]
I don't know why, but the worklet not works for me.

https://deploy-preview-131--keen-thompson-a26224.netlify.app/

noise

**Comment by jh3y** [comment]
Yeah, not quite sure what happened there 🤔 

The packager seemed to lose the `getRandom` method. I've updated the polyfill link on the demo too 👍

**Review by nucliweb — APPROVED** [review]

**Comment by jh3y** [comment]
I did have a question about the polyfill for FireFox. It's working on `houdini.how` but not in my demo and I'm not overly sure why. It never seems to hit `paint`.

**Comment by developit** [comment]
@jh3y you need to use css-paint-polyfill@3 - `npm install css-paint-polyfill@next`. The current release version is 2.0 but it is old.

**Comment by developit** [comment]
The registerProperty issue is because we are doing a gross thing and trying to first load paint worklets as script on the main thread, then intercepting calls to registerPaint and proxying them to a blob worklet. I can fix that, not sure when though.

**Comment by jh3y** [comment]
Oh no. That's fine, I've got the polyfill working. But, I can't see why in my demo on Firefox, the paint isn't applied if I wrap the style in `@supports` 🤔 

https://codepen.io/jh3y/pen/LYRxQrQ

If I take the @supports out and change the sliders, it will trigger a paint.

**Comment by nucliweb** [comment]
You can force the "repaint" adding the line after the `const WAND=...`

```js
const WAND = document.querySelector('.wand');
WAND.style.setProperty('--noise-cell-size', CONFIG.SIZE+0)
```

**Comment by jh3y** [comment]
Awesome. Sorted! 🎉

**Pull request merged**
